### ISSUE TITLE
Ideas for your package

### ISSUE THREAD

**Issue by Kostasn2** [papierkorp/sublime-templ#1]
Hello, i saw your package on a pull request on package control channel.

Since iam also a developer and deploying also syntax packages to sublime, a nice addition is to add code snippets for your syntax, and also you can add folding preferences (you know the arrow that folds functions etc on big programs).

**Comment by papierkorp** [comment]
I will take a look into it, already had a long fight to figure out how to make this work :D

But it certainly makes sense.

**Comment by Kostasn2** [comment]
If you need any help, you can view my snippets on my packages on github, or you can get in touch with me to help you.
